name: Test

# Build on a pull request
on:
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.x'

      - name: Setup kramdown-rfc
        run: gem install kramdown-rfc

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Setup xml2rfc
        run: pip install xml2rfc

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Make
        run: make
